### PR TITLE
added divide function and test

### PR DESCRIPTION
**Pull request by alligalli**

### CODE REVIEW

**Review by yauh-ask — COMMENTED** [review]
I am not sure I agree with no "calc" there

**Comment by alligalli** [comment]
our file is called main! not calc, so that calc should be changed to main anyway
by importing the functions from main.py like so:

`from main import divide, add, subtract, etc`

you can reference them in the file with their direct name

**Comment by yauh-ask** [comment]
> our file is called main! not calc, so that calc should be changed to main anyway
> by importing the functions from main.py like so:
> 
> `from main import divide, add, subtract, etc`
> 
> you can reference them in the file with their direct name

I approve!

**Review by yauh-ask — APPROVED** [review]
Good for me

**Review by yauh-ask — COMMENTED** [review]
maybe, main?

**Pull request merged**
