### PR TITLE
Nina

### PR DESCRIPTION
**Pull request by yauh-ask**

### CODE REVIEW

**Review by alligalli — CHANGES_REQUESTED** [review]
main.py should be refactored into a subtract function

**Comment by alligalli** [comment]
> 
> 
> main.py should be refactored into a subtract function

like so:

```
def subtract(x, y):
    """Subtract Function"""
    return x - y
```

**Review by alligalli — APPROVED** [review]
now it's super better, even more testable because it's a function, looks good to me

**Review by nikje27 — COMMENTED** [review]
better

**Comment by alligalli** [comment]
solved conflicts, have a double check again to see it's all ok

**Review by yauh-ask — COMMENTED** [review]
oki

**Pull request merged**
